apiVersion: v1
kind: PersistentVolume
metadata:
  name: s2v-persistent-volume
  labels:
    id: s2v
spec:
  accessModes:
  - ReadOnlyMany
  volumeMode: Filesystem
  storageClassName: ebs-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  awsElasticBlockStore:
    fsType: xfs
    readOnly: true
    volumeID: vol-00083366c9bd12ad3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s2v-persistent-volume-claim
  labels:
    id: s2v
spec:
  accessModes:
  - ReadOnlyMany
  volumeMode: Filesystem
  volumeName: s2v-persistent-volume
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 100Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: s2v-test-job
  labels:
    id: s2v
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        id: s2v
    spec:
      containers:
      - name: s2v-test
        image: docker.pkg.github.com/iprova/docker-common/sent2vec
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          subPath: models
          mountPath: /models
          readOnly: true
        - name: data
          subPath: sentences
          mountPath: /sentences
          readOnly: true
        #args: ["test-s2v", "torontobooks_unigrams"]
        args: ["test-s2v", "wiki_bigrams"]
        resources: {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: s2v-persistent-volume-claim
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: github-docker-registry
